sonar.projectKey=ellandar31_astreintes
sonar.organization=ellandar31

sonar.sources=src
sonar.tests=src

sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**

sonar.javascript.lcov.reportPaths=coverage/astreintes/lcov.info

sonar.sourceEncoding=UTF-8
